### ISSUE TITLE
mextr: index out of bounds error 

### ISSUE THREAD

**Issue by IsmailM** [heathsc/gemBS-rs#7]
Hi Simon,

We are trying to run `gemBS extract` and are seeing the following error. Do you have any suggestions on how to get around this?

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 2 but the index is 2', mextr/src/bbi/tree.rs:125:41
```

The full output is below:

```
$ gemBS extract  --cpg --barcode P2_BDDM200000221-1A_HJWYLDSXY
INFO - Launch:
	/usr/local/lib/gemBS/bin/mextr --loglevel info --compress --md5 --regions-file /scratch/secker/dnmt3a/gembs/extract/P2_BDDM200000221-1A_HJWYLDSXY/P2_BDDM200000221-1A_HJWYLDSXY_mextr_ctgs.bed --cpgfile /scratch/secker/dnmt3a/gembs/extract/P2_BDDM200000221-1A_HJWYLDSXY/P2_BDDM200000221-1A_HJWYLDSXY_cpg.txt.gz --bed-methyl /scratch/secker/dnmt3a/gembs/extract/P2_BDDM200000221-1A_HJWYLDSXY/P2_BDDM200000221-1A_HJWYLDSXY --tabix --threads 1 --threshold 10 --mode strand-specific /scratch/secker/dnmt3a/gembs/calls/P2_BDDM200000221-1A_HJWYLDSXY/P2_BDDM200000221-1A_HJWYLDSXY.bcf
WARN - Removing output file /scratch/secker/dnmt3a/gembs/extract/P2_BDDM200000221-1A_HJWYLDSXY/P2_BDDM200000221-1A_HJWYLDSXY_cpg.txt.gz
WARN - Removing output file /scratch/secker/dnmt3a/gembs/extract/P2_BDDM200000221-1A_HJWYLDSXY/P2_BDDM200000221-1A_HJWYLDSXY_cpg.bed.gz
WARN - Removing output file /scratch/secker/dnmt3a/gembs/extract/P2_BDDM200000221-1A_HJWYLDSXY/P2_BDDM200000221-1A_HJWYLDSXY_cpg.bb
WARN - Removing output file /scratch/secker/dnmt3a/gembs/extract/P2_BDDM200000221-1A_HJWYLDSXY/P2_BDDM200000221-1A_HJWYLDSXY_chg.bed.gz
WARN - Removing output file /scratch/secker/dnmt3a/gembs/extract/P2_BDDM200000221-1A_HJWYLDSXY/P2_BDDM200000221-1A_HJWYLDSXY_chg.bb
WARN - Removing output file /scratch/secker/dnmt3a/gembs/extract/P2_BDDM200000221-1A_HJWYLDSXY/P2_BDDM200000221-1A_HJWYLDSXY_chh.bed.gz
WARN - Removing output file /scratch/secker/dnmt3a/gembs/extract/P2_BDDM200000221-1A_HJWYLDSXY/P2_BDDM200000221-1A_HJWYLDSXY_chh.bb
ERROR - Error received from worker thread 7
ERROR - Worker thread 0 received error: receiving on a closed channel
ERROR - Worker thread 4 received error: receiving on a closed channel
ERROR - Worker thread 6 received error: receiving on a closed channel
ERROR - Worker thread 5 received error: receiving on a closed channel
ERROR - Worker thread 2 received error: receiving on a closed channel
ERROR - Worker thread 1 received error: receiving on a closed channel
ERROR - Worker thread 3 received error: receiving on a closed channel
Error: "Exiting after error"


$ /usr/local/lib/gemBS/bin/mextr --loglevel info --compress --md5 --regions-file /scratch/secker/dnmt3a/gembs/extract/P2_BDDM200000221-1A_HJWYLDSXY/P2_BDDM200000221-1A_HJWYLDSXY_mextr_ctgs.bed --cpgfile /scratch/secker/dnmt3a/gembs/extract/P2_BDDM200000221-1A_HJWYLDSXY/P2_BDDM200000221-1A_HJWYLDSXY_cpg.txt.gz --bed-methyl /scratch/secker/dnmt3a/gembs/extract/P2_BDDM200000221-1A_HJWYLDSXY/P2_BDDM200000221-1A_HJWYLDSXY --tabix --threads 1 --threshold 10 --mode strand-specific /scratch/secker/dnmt3a/gembs/calls/P2_BDDM200000221-1A_HJWYLDSXY/P2_BDDM200000221-1A_HJWYLDSXY.bcf
INFO - compress_bbi_thread starting up
INFO - write_bbi_thread starting up
thread '<unnamed>' panicked at 'index out of bounds: the len is 2 but the index is 2', mextr/src/bbi/tree.rs:125:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
````

**Comment by IsmailM** [comment]
Came across this again. It's due to a conflict between gemBS v3 and v4 - i.e. the `mextr` script from v3 was called instead of the updated version from v4.

Perhaps it makes sense to check the version of mextr (or rename the script in v4) to avoid this issue)...

**Comment by heathsc** [comment]
Thanks for the report.  Could you give me more details on how exactly this
is triggered.  At the least I can try and give a more informative error
message!

Simon
